import { api } from '../../api'
import { Link } from '../../app/router'
import { useApiResource } from '../../hooks/useApiResource'
import { Badge } from '../../components/Badge'
import { EmptyState, ErrorState, LoadingState } from '../../components/AsyncState'
import { Disclosure } from '../../components/Disclosure'
import { Prose } from '../../components/Prose'
import { formatTimestamp } from '../../lib/format'
import { usePaperTitles } from './usePaperTitles'

/**
 * Detail of one Schema Wiki page.
 *
 * The page title, summary, Schema identity, and build state are rendered exactly
 * as the Wiki pages endpoint reports them, and the source paper is resolved
 * through the Papers API for a readable label. The frontend never derives Wiki
 * knowledge itself (REQ-010 / C-002).
 */
export function WikiPageDetailView({
  workspaceId,
  pageId,
}: {
  workspaceId: string
  pageId: string
}) {
  const page = useApiResource(
    (signal) => api.wiki.page(workspaceId, pageId, { signal }),
    [workspaceId, pageId],
  )
  const { titles, loading: titlesLoading } = usePaperTitles()

  if (page.status === 'loading') {
    return <LoadingState label="Loading Schema Wiki page…" />
  }
  if (page.status === 'error') {
    return <ErrorState error={page.error} title="Schema Wiki page unavailable" onRetry={page.reload} />
  }

  const record = page.data
  if (!record) {
    return (
      <EmptyState
        title="Wiki page not found"
        description="The backend did not return this Schema Wiki page for the open workspace."
      />
    )
  }

  const paperTitle = titles.get(record.paper_id)
  const paperLabel = paperTitle ?? record.paper_id

  return (
    <div className="stack" data-testid="wiki-page-detail">
      <div className="context-card">
        <div className="card__title-row">
          <h3 className="card__title">{record.title}</h3>
          <Badge tone="info">Schema Wiki</Badge>
          <Badge
            tone={record.build_status === 'complete' ? 'success' : 'neutral'}
            testId="wiki-page-build-status"
          >
            {record.build_status}
          </Badge>
        </div>
        <p className="card__meta" data-testid="wiki-page-identity">
          {record.schema_id}@{record.schema_version} · build revision {record.build_revision} ·
          updated {formatTimestamp(record.updated_at)}
        </p>
        <Prose text={record.summary} testId="wiki-page-summary" />
      </div>

      <div className="subsection" data-testid="wiki-page-source-paper">
        <h3 className="subsection__title">Source paper</h3>
        <p className="card__meta">
          This page is generated by the backend from the workspace paper{' '}
          <Link to={`/library/${encodeURIComponent(record.paper_id)}`}>{paperLabel}</Link>.
        </p>
        {!paperTitle ? (
          <p className="card__meta">
            {titlesLoading
              ? 'Reading the paper title from the Library…'
              : 'The Library did not report a title for this paper, so its identifier is shown.'}
          </p>
        ) : null}
      </div>

      <div className="subsection" data-testid="wiki-page-build-details">
        <h3 className="subsection__title">Schema Wiki build</h3>
        <dl className="detail-list">
          <div className="detail-list__row">
            <dt>Schema</dt>
            <dd>
              {record.schema_id} version {record.schema_version}
            </dd>
          </div>
          <div className="detail-list__row">
            <dt>Build status</dt>
            <dd>{record.build_status}</dd>
          </div>
          <div className="detail-list__row">
            <dt>Build revision</dt>
            <dd>{record.build_revision}</dd>
          </div>
          <div className="detail-list__row">
            <dt>Created</dt>
            <dd>{formatTimestamp(record.created_at)}</dd>
          </div>
          <div className="detail-list__row">
            <dt>Updated</dt>
            <dd>{formatTimestamp(record.updated_at)}</dd>
          </div>
        </dl>
      </div>

      <Disclosure summary="Record identifiers" testId="wiki-page-identifiers">
        <dl className="detail-list">
          <div className="detail-list__row">
            <dt>Wiki page</dt>
            <dd>
              <code>{record.page_id}</code>
            </dd>
          </div>
          <div className="detail-list__row">
            <dt>Workspace</dt>
            <dd>
              <code>{record.workspace_id}</code>
            </dd>
          </div>
          <div className="detail-list__row">
            <dt>Source paper</dt>
            <dd>
              <code>{record.paper_id}</code>
            </dd>
          </div>
        </dl>
      </Disclosure>
    </div>
  )
}
