"""create_stage1_core_tables

Revision ID: 364661401d4d
Revises: 
Create Date: 2026-07-24 13:04:53.430048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364661401d4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('normalized_title', sa.String(length=1024), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=512), nullable=True),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('normalized_doi', sa.String(length=256), nullable=True),
    sa.Column('arxiv_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_papers_arxiv_id', 'papers', ['arxiv_id'], unique=False)
    op.create_index('ix_papers_normalized_doi', 'papers', ['normalized_doi'], unique=False)
    op.create_index('ix_papers_normalized_title', 'papers', ['normalized_title'], unique=False)
    op.create_index('ix_papers_status', 'papers', ['status'], unique=False)
    op.create_table('paper_authors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('paper_id', sa.String(length=32), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('normalized_name', sa.String(length=512), nullable=True),
    sa.Column('affiliation', sa.String(length=1024), nullable=True),
    sa.Column('orcid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_authors_normalized_name', 'paper_authors', ['normalized_name'], unique=False)
    op.create_table('paper_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('paper_id', sa.String(length=32), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('stored_filename', sa.String(length=512), nullable=True),
    sa.Column('relative_path', sa.String(length=1024), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('pdf_version', sa.String(length=16), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('is_scanned_candidate', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path', name='uq_paper_files_relative_path'),
    sa.UniqueConstraint('sha256', name='uq_paper_files_sha256')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('uploaded_filename', sa.String(length=512), nullable=True),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('file_id', sa.String(length=32), nullable=True),
    sa.Column('paper_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['paper_files.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_status', 'ingestion_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_jobs_status', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('paper_files')
    op.drop_index('ix_paper_authors_normalized_name', table_name='paper_authors')
    op.drop_table('paper_authors')
    op.drop_index('ix_papers_status', table_name='papers')
    op.drop_index('ix_papers_normalized_title', table_name='papers')
    op.drop_index('ix_papers_normalized_doi', table_name='papers')
    op.drop_index('ix_papers_arxiv_id', table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
