"""create_metadata_candidates

Revision ID: 5a7bec75e342
Revises: 364661401d4d
Create Date: 2026-07-24 16:02:27.332013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7bec75e342'
down_revision: Union[str, Sequence[str], None] = '364661401d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_candidates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('paper_id', sa.String(length=32), nullable=False),
    sa.Column('paper_file_id', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('value_text', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_location', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_file_id'], ['paper_files.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metadata_candidates_field_name', 'metadata_candidates', ['field_name'], unique=False)
    op.create_index('ix_metadata_candidates_is_selected', 'metadata_candidates', ['is_selected'], unique=False)
    op.create_index('ix_metadata_candidates_paper_file_id', 'metadata_candidates', ['paper_file_id'], unique=False)
    op.create_index('ix_metadata_candidates_paper_id', 'metadata_candidates', ['paper_id'], unique=False)
    op.create_index('ix_metadata_candidates_source_type', 'metadata_candidates', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metadata_candidates_source_type', table_name='metadata_candidates')
    op.drop_index('ix_metadata_candidates_paper_id', table_name='metadata_candidates')
    op.drop_index('ix_metadata_candidates_paper_file_id', table_name='metadata_candidates')
    op.drop_index('ix_metadata_candidates_is_selected', table_name='metadata_candidates')
    op.drop_index('ix_metadata_candidates_field_name', table_name='metadata_candidates')
    op.drop_table('metadata_candidates')
    # ### end Alembic commands ###
